name: Main

on: push

jobs:
  my-job:
    name: Publish to surge
    runs-on: ubuntu-latest
    steps:
      - name: Publish to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'static-assets-technikhil314.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}